### ISSUE TITLE
how to place a pdf as a template

### ISSUE THREAD

**Issue by DesarrolloSiget** [mccarlosen/laravel-mpdf#25]
Hello,

I am need place a pdf as a template.

I wrote the code with some changes, check if it works, use them

![imagen](https://user-images.githubusercontent.com/49963285/65255965-6259ac80-dac4-11e9-8f4f-c95648e3bc72.png)

**Comment by mccarlosen** [comment]
Interesting, I tried it and I will add it in the next update. The SetImportUse method became obsolete in mpdf v8.

![image](https://user-images.githubusercontent.com/8524361/66792735-a96a7000-eebf-11e9-91d6-d9f5c442617b.png)

https://mpdf.github.io/reference/mpdf-functions/setimportuse.html#description

**Comment by simadesign** [comment]
I added the changes to my code. Also the changes to "LaravelMpdfWrapper.php" to parse the sourcePDF variable to the script above.

I don't know if the problem comes from the new 8.0 Version, but nothing happens if I use "SetPageTemplate" or "SetDocTemplate". Only code I can use is:

		$pagecount = $this->mpdf->setSourceFile($sourcePdf);
		$tplId = $this->mpdf->importPage($pagecount);
		$this->mpdf->useTemplate($tplId);

But this code only puts the source-PDF to one page.
